In [1]:
import pandas as pd

In [2]:
kk = pd.read_stata("kk.dta")
spouses = pd.read_stata("spouses.dta")
village_treat = pd.read_stata("village_treat.dta")
waveI_households = pd.read_stata("waveI_households.dta")
waveII = pd.read_stata("waveII.dta", convert_categoricals = False)
waveIII_young_women_sample = pd.read_stata("waveIII_young_women_sample.dta", convert_categoricals = False)
waveIII = pd.read_stata("waveIII.dta", convert_categoricals = False)

In [3]:
kk

      month villagecode  enroll  CLUSTER  total_girls   cycle
0     may08      181202    40.0      375          137  cycle1
1     apr08      181202    40.0      375          137  cycle1
2     mar08      181202    40.0      375          137  cycle1
3     dec07      181202    40.0      375          137  cycle1
4     jun08      181202    40.0      375          137  cycle1
...     ...         ...     ...      ...          ...     ...
5198  feb10      957407    37.0      373          243  cycle4
5199  jan10      957407    37.0      373          243  cycle4
5200  jun10      957407    34.0      373          243  cycle4
5201  mar10      957407    37.0      373          243  cycle4
5202  may10      957407    37.0      373          243  cycle4

[5203 rows x 6 columns]

In [4]:
spouses

,girlID,resp_status,consent,cchar_marriage1,cchar_marriage2
0,181202001105,2,NaN,NaN,NaN
1,181202003504,2,NaN,NaN,NaN
2,181202013703,2,NaN,NaN,NaN
3,181203007403,2,NaN,NaN,NaN
4,181203008704,2,NaN,NaN,NaN
...,...,...,...,...,...
4316,957408029403,1,1.0,Looks/attractiveness,Knows how to do housework
4317,957408032004,1,1.0,Education,Knows how to do housework
4318,957408032005,2,NaN,NaN,NaN
4319,957408032104,1,1.0,Like-mindedness/Romantic,Temperament/Nature
4320,963509002703,2,NaN,NaN,NaN

In [5]:
village_treat

    villagecode                       treatment_type
0        181202  KK + Financial Literacy + Incentive
1        181203              KK + Financial Literacy
2        181204                              Control
3        181402                              Control
4        181403              KK + Financial Literacy
..          ...                                  ...
455      957402                              Control
456      957403              KK + Financial Literacy
457      957404                              Control
458      957407  KK + Financial Literacy + Incentive
459      957408                            Incentive

[460 rows x 2 columns]

In [6]:
waveI_households

,HHID,age_reported,ever_married,economic_status,adolescence_period,sisters,brothers,school_skill,right_spouse,society_pressure,reputation,matchmaker,age_married_desired,child
0,313020215,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes
1,313020646,13.0,No,No,Yes,No,No,No,No,Yes,No,No,18.0,Yes
2,313020104,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes
3,313020152,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes
4,313020571,50.0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70527,9574020422,11.0,No,Yes,Yes,No sister,No brother,No,Yes,No,No,Yes,NaN,Yes
70528,9574020139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes
70529,9574020310,53.0,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No
70530,9574020348,5.0,No,No,Yes,No,No,Yes,Yes,No,No,Yes,NaN,Yes
70531,9574020054,11.0,No,No,No,Yes,Yes,Yes,No,No,No,No,18.0,Yes

In [7]:
waveII

,girlID,HHID,CLUSTER,unionID,washedout,treatment_type,third,midline,ml_ever_married,ml_still_in_school,...,bl_age15,bl_age16,bl_age17,bl_public_transit,before_miss,older_sister_miss,bl_still_in_school_miss,bl_education_mother_miss,bl_HHsize_miss,bl_public_transit_miss
0,31301024503,313010245,1,313.0,0.0,1.0,2.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
1,31301020104,313010201,1,313.0,0.0,1.0,2.0,1.0,1.0,0.0,...,0.0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,31301035004,313010350,1,313.0,0.0,1.0,2.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
3,31301004805,313010048,1,313.0,0.0,1.0,2.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
4,31301025702,313010257,1,313.0,0.0,1.0,2.0,1.0,1.0,0.0,...,1.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79345,189409025004,1894090250,460,1894.0,0.0,4.0,2.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
79346,189409006605,1894090066,460,1894.0,0.0,4.0,2.0,1.0,NaN,1.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
79347,189409002803,1894090028,460,1894.0,0.0,4.0,2.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
79348,189409007107,1894090071,460,1894.0,0.0,4.0,2.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0
79349,189409031103,1894090311,460,1894.0,0.0,4.0,2.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,1.0,0.0,0.0

In [8]:
waveIII_young_women_sample

,girlID,HHID,CLUSTER,bl_age_reported,unionID,washedout,treatment_type,at1,at2,at3,...,bl_education_mother_miss,bl_HHsize_miss,bl_public_transit_miss,bl_bmi_miss,bl_stunted_miss,bl_income_miss,g_cons_index,high_g_cons,distance_hh_oil_miss,g_cons_index_miss
0,31301013404,313010134,1.0,12,313.0,0,1.0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.145950,0.0,0.0,0.0
1,31301002505,313010025,1.0,16,313.0,0,1.0,1,0,0,...,1.0,0.0,0.0,1.0,1.0,0.0,-0.481473,0.0,0.0,0.0
2,31301038806,313010388,1.0,14,313.0,0,1.0,1,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,-0.346383,0.0,1.0,0.0
3,31301034203,313010342,1.0,14,313.0,0,1.0,1,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,-0.402854,0.0,0.0,0.0
4,31301002506,313010025,1.0,13,313.0,0,1.0,1,0,0,...,1.0,0.0,0.0,1.0,1.0,0.0,-0.755461,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,189409018903,1894090189,460.0,13,1894.0,0,4.0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.879384,1.0,0.0,0.0
7263,189409003705,1894090037,460.0,14,1894.0,0,4.0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.290699,1.0,0.0,0.0
7264,189409000303,1894090003,460.0,10,1894.0,0,4.0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.012859,1.0,0.0,0.0
7265,189409010903,1894090109,460.0,10,1894.0,0,4.0,0,0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.555591,1.0,0.0,0.0
7266,189409018504,1894090185,460.0,14,1894.0,0,4.0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.031599,1.0,0.0,0.0

In [9]:
waveIII

,girlID,HHID,CLUSTER,bl_age_reported,unionID,washedout,missing_village,treatment_type,at1,at2,...,vill_radius_500_oil,village_distance,matchmaker,matchmaker_3,older_sister_miss,bl_still_in_school_miss,bl_education_mother_miss,bl_HHsize_miss,bl_public_transit_miss,bl_ever_married
0,181202000105,1812020001,375.0,16.0,1812.0,0.0,0.0,3.0,0,0,...,1.0,1245.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,181202000604,1812020006,375.0,12.0,1812.0,0.0,0.0,3.0,0,0,...,1.0,1245.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,181202000806,1812020008,375.0,14.0,1812.0,0.0,0.0,3.0,0,0,...,1.0,1245.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,181202001003,1812020010,375.0,11.0,1812.0,0.0,0.0,3.0,0,0,...,1.0,1245.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,181202001106,1812020011,375.0,16.0,1812.0,0.0,0.0,3.0,0,0,...,1.0,1245.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109093,957408008703,9574080087,374.0,16.0,9574.0,NaN,NaN,2.0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
109094,957408015602,9574080156,374.0,16.0,9574.0,NaN,NaN,2.0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
109095,957408021402,9574080214,374.0,16.0,9574.0,NaN,NaN,2.0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
109096,957408028104,9574080281,374.0,16.0,9574.0,NaN,NaN,2.0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
109097,957408028704,9574080287,374.0,15.0,9574.0,NaN,NaN,2.0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0